import json

preHTML = """
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{cidade_nome}</title>
        <meta charset="UTF-8">
        <meta nome="viewport" content="width=device-width, initial-scale=1" >
        <link rel="stylesheet" href="../w3.css">
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-purple">
                <h3>{cidade_nome}</h3>
            </header>
            <div class="w3-container">
"""

posHTML = """
            </div>
            <footer class="w3-container w3-purple">
                <h5>Generated by CidadesDeBraga::EngWeb2024::A100705</h5>
                <address>
                    <a href="/">Voltar à página principal</a>
                </address>
            </footer>
        </div>
    </body>
</html>
"""

def getLigacoes(cidade):
    ligacoes = []
    for ligacao in data['ligacoes']:
        if ligacao['origem'] == cidade['id']:
            ligacoes.append(ligacao)
    return ligacoes

def generateContent(cidade):
    content = "<p><h2>População</h2> " + str(cidade['população']) + " pessoas. </p>"
    content += "<p><h2>Descrição</h2> " + cidade['descrição'] + "</p>"
    content += "<p><h2>Distrito</h2> " + cidade['distrito'] + "</p>"

    cidadeLigacoes = getLigacoes(cidade)

    if len(cidadeLigacoes) > 0:
        content += "<h2>Ligações</h2>"
        content += "<ul>"
        for ligacao in cidadeLigacoes:
            cidadeDestino = next((item for item in cities if item["id"] == ligacao['destino']), None)
            content += "<li><a href=" + cidadeDestino['id'] + ">" + cidadeDestino['nome'] + "</a> (" + str(ligacao['distância']) + " km)</li>"
        content += "</ul>"
    else:
        content += "<h2>Ligações</h2>"
        content += "<p>Não existem ligações a outras cidades.</p>"
    return content

content = ""
with open('mapa-virtual.json') as f:
    data = json.load(f)
    cities = sorted(data['cidades'], key=lambda x: x['nome'])
    for cidade in cities:
        cidade_nome = cidade['nome'] + " " + cidade['distrito']
        content = generateContent(cidade)
        pageHTML = preHTML.format(title=cidade_nome, cidade_nome=cidade_nome) + content + posHTML
        f = open('./cidadesSite/' + cidade['id'] + '.html', 'w')
        f.write(pageHTML)
        f.close()