import json

preHTML = """
<!DOCTYPE html>
<html lang="en">

    <head>
        <title>Cidades de Portugal</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1" >
        <link rel="stylesheet" href="../w3.css">
    </head>

    <body>

        <div class="w3-card-4">

            <header class="w3-container w3-purple">
                <h3>Cidades de Portugal</h3>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
"""

posHTML = """
                </ul>
            </div>

            <footer class="w3-container w3-purple">
                <h5>Generated by CidadesDePortugal::EngWeb2024::A100705</h5>
            </footer>

        </div>

    </body>

</html>
"""

content = ""
with open('mapa-virtual.json') as f:
    data = json.load(f)
    cities = sorted(data['cidades'], key=lambda x: x['nome'])
    for cidade in cities:
        content += "<li><a href=\"./" + cidade['id'] + "\">" + cidade['nome'] + " (" + cidade['distrito'] + ")""</a></li>\n"

pageHTML = preHTML + content + posHTML

f = open('./cidadesSite/index.html', 'w')
f.write(pageHTML)
f.close()